version: '3'

services:

  rad-info-tracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rad-info-tracker-db
    networks:
      - my-network

  rad-info-tracker-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge