version: '3'

services:

  rad-info-tracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/radInfoTracker/files:/opt/radInfoTracker/files
    ports:
      - "8040:8080"
    depends_on:
      - rad-info-tracker-db
    networks:
      - my-network

  rad-info-tracker-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testing_db
      POSTGRES_USER: radInfo
      POSTGRES_PASSWORD: radInfo2023
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge