name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          test -d ~/.ssh || mkdir -p ~/.ssh
          test -e ~/.ssh/radtracker_key.pem || touch ~/.ssh/radtracker_key.pem
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/radtracker_key.pem
          chmod 400 ~/.ssh/radtracker_key.pem
          test -e ~/.ssh/known_hosts || touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts

      - name: Check if directory exists on the server
        run: |
          ssh -i ~/.ssh/radtracker_key.pem  ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} '[ -d rad-info-tracker/ ] && cd rad-info-tracker && git pull || git clone https://github.com/N-Pacis/rad-info-tracker.git rad-info-tracker/'

      - name: Install Docker and Docker Compose on the server
        run: |
          ssh -i ~/.ssh/radtracker_key.pem ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} '
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
          '

      - name: Run Docker Compose Command
        run: |
          ssh -i ~/.ssh/radtracker_key.pem ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} '
            cd rad-info-tracker
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
          '